[package]
name = "gdbstub"
version = "0.1.0"
authors = ["Dylan Reid <dgreid@chromium.org>"]
edition = "2018"

[lib]
path = "src/gdbstub.rs"

[dependencies]

[dev-dependencies]
libc="*"
sys_util = {path="../sys_util"}
