[package]
name = "arch"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
devices = { path = "../devices" }
io_jail = { path = "../io_jail" }
kvm = { path = "../kvm" }
sys_util = { path = "../sys_util" }
resources = { path = "../resources" }
kernel_cmdline = { path = "../kernel_cmdline" }
libc = "*"
