[package]
name = "qcow_utils"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[lib]
path = "src/qcow_utils.rs"
crate-type = ["cdylib"]

[[bin]]
name = "qcow_img"
path = "src/qcow_img.rs"

[dependencies]
getopts = "*"
libc = "*"
qcow = { path = "../qcow" }
sys_util = { path = "../sys_util" }

[dev-dependencies]
qcow_utils_test = { path = "tests/qcow_utils_test" }
